#ifndef  DEF_UI_COLOURS
#define  DEF_UI_COLOURS

typedef  enum
{
    BACKGROUND_COLOUR,
    BUTTON_ACTIVE_COLOUR,
    BUTTON_INACTIVE_COLOUR,
    BUTTON_PUSHED_COLOUR,
    BUTTON_TEXT_COLOUR,
    TEXT_ENTRY_ACTIVE_COLOUR,
    TEXT_ENTRY_INACTIVE_COLOUR,
    TEXT_ENTRY_EDIT_COLOUR,
    TEXT_ENTRY_EDIT_TEXT_COLOUR,
    TEXT_ENTRY_TEXT_COLOUR,
    TEXT_ENTRY_CURSOR_COLOUR,
    LABEL_ACTIVE_COLOUR,
    LABEL_INACTIVE_COLOUR,
    LABEL_TEXT_COLOUR,
    SLIDER_ACTIVE_COLOUR,
    SLIDER_INACTIVE_COLOUR,
    SLIDER_PEG_COLOUR,
    N_UI_COLOURS
} UI_colours;

#endif
